// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIh-5nhPcgRFooOUFD5mUUSfY2LcA-9k4',
    appId: '1:836574435325:web:bfbd381cc23c2921742b94',
    messagingSenderId: '836574435325',
    projectId: 'smartcom-pharmacy-app',
    authDomain: 'smartcom-pharmacy-app.firebaseapp.com',
    storageBucket: 'smartcom-pharmacy-app.appspot.com',
    measurementId: 'G-HTQVT05R5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS9KkTiu63JDtf_igc65iyOiAo_HSxdlQ',
    appId: '1:836574435325:android:e6c0175cc472fbf0742b94',
    messagingSenderId: '836574435325',
    projectId: 'smartcom-pharmacy-app',
    storageBucket: 'smartcom-pharmacy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZuYeE9NmFsLt-HW1ctjuYxRHlKLHKWbk',
    appId: '1:836574435325:ios:2293cbaad2630be8742b94',
    messagingSenderId: '836574435325',
    projectId: 'smartcom-pharmacy-app',
    storageBucket: 'smartcom-pharmacy-app.appspot.com',
    iosClientId: '836574435325-jg9vt4u28ur8re7q7fpngciu8hb6r9b3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharnacy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZuYeE9NmFsLt-HW1ctjuYxRHlKLHKWbk',
    appId: '1:836574435325:ios:2293cbaad2630be8742b94',
    messagingSenderId: '836574435325',
    projectId: 'smartcom-pharmacy-app',
    storageBucket: 'smartcom-pharmacy-app.appspot.com',
    iosClientId: '836574435325-jg9vt4u28ur8re7q7fpngciu8hb6r9b3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharnacy',
  );
}
